# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = "Hack Nerd Font"

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Downloads/wallhaven-6lyo7x_3840x2160.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 10%, 3%
    outline_thickness = 2
    outer_color = rgba(ffcf8cee) # no fill

    inner_color = rgba(e62955ee)
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(00ff99ee) rgba(ff6633ee) 120deg

    font_color = rgb(ffcf8c)
    fail_color = rgb(ffcf8c)
    fade_on_empty = false
    rounding = 7

    font_family = $font
    placeholder_text = Type that password you use for everything else...
    fail_text = Let's pretend that didn't happen. Retry.

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.1
    dots_spacing = 0.5

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

